// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDavWzLTNy5qwIhEBBLJOBroJDJkpF6G3Y',
    appId: '1:1058367735381:web:d5442e962f862c7de776dc',
    messagingSenderId: '1058367735381',
    projectId: 'trackify-55ef7',
    authDomain: 'trackify-55ef7.firebaseapp.com',
    storageBucket: 'trackify-55ef7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSHNUic6-jV0XjZF_BGLnKXf0Ef8bxSsg',
    appId: '1:1058367735381:android:667df98b99e2fed5e776dc',
    messagingSenderId: '1058367735381',
    projectId: 'trackify-55ef7',
    storageBucket: 'trackify-55ef7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjtbHSCSKPn64bvaDTA5PA-MJr9fhis2Y',
    appId: '1:1058367735381:ios:9ed210ba87eda615e776dc',
    messagingSenderId: '1058367735381',
    projectId: 'trackify-55ef7',
    storageBucket: 'trackify-55ef7.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjtbHSCSKPn64bvaDTA5PA-MJr9fhis2Y',
    appId: '1:1058367735381:ios:9ed210ba87eda615e776dc',
    messagingSenderId: '1058367735381',
    projectId: 'trackify-55ef7',
    storageBucket: 'trackify-55ef7.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDavWzLTNy5qwIhEBBLJOBroJDJkpF6G3Y',
    appId: '1:1058367735381:web:889b33688024e958e776dc',
    messagingSenderId: '1058367735381',
    projectId: 'trackify-55ef7',
    authDomain: 'trackify-55ef7.firebaseapp.com',
    storageBucket: 'trackify-55ef7.firebasestorage.app',
  );
}
